name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Set Node options for OpenSSL
      run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
        
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      
    - name: Install specific packages
      run: npm install crypto-js --save
      
    - name: Manual Build and Deploy
      run: |
        npm run build
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        npx gh-pages -d build -u "GitHub Actions <actions@github.com>"
      env:
        CI: false
